apiVersion: v2
name: k8tz
description: Kubernetes admission controller to inject timezones into Pods and CronJobs
version: 0.16.1
appVersion: "0.16.1"
icon: https://github.com/k8tz/k8tz/raw/master/assets/k8tz-icon-transparent.png
home: http://k8tz.io
sources:
  - https://github.com/k8tz/k8tz
keywords:
  - timezone
  - timezones
  - admission
  - controller
  - tzdata
  - tzdb
annotations:
  artifacthub.io/changes: |
    - kind: "added"
      description: "Add possibility to set init container resources"
  artifacthub.io/links: |
    - name: "source"
      url: "https://github.com/k8tz/k8tz"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: "Apache-2.0"
